SELECT * FROM TAB;

SHOW USER;

CREATE TABLE PROFESSOR(
PROFNO      NUMBER(5) NOT NULL,
NAME        VARCHAR2(10) NOT NULL,
ENAME       VARCHAR2(20) NOT NULL,
POSITION    VARCHAR2(20) NOT NULL,
SAL         NUMBER(4) NOT NULL,
HIREDATE    DATE NOT NULL,
AGE         NUMBER(3) NOT NULL,
DEPTNO      NUMBER(3) NOT NULL,
CONSTRAINT PROFESSOR_PK PRIMARY KEY(PROFNO)
);

ALTER TABLE PROFESSOR ADD CONSTRAINT PROFESSOR_FK
FOREIGN KEY(DEPTNO)
REFERENCES DEPARTMENT(DEPTNO);

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_CONSTRAINT_NAME, STATUS FROM USER_CONSTRAINTS WHERE TABLE_NAME='DEPARTMENT';

COMMIT;

SELECT * FROM DEPARTMENT;
SELECT * FROM PROFESSOR;

SELECT A.NAME, A.PROFNO, A.POSITION, B.DNAME FROM PROFESSOR A, DEPARTMENT B WHERE  A.DEPTNO=B.DEPTNO AND A.DEPTNO=203;