-- 게시판 테이블
CREATE TABLE BOARD (
NUM NUMBER(7) NOT NULL,
WRITER VARCHAR2(12) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
SUBJECT VARCHAR2(50) NOT NULL,
PASS VARCHAR2(10) NOT NULL,
READCOUNT NUMBER(5) DEFAULT 0 NOT NULL,
REF NUMBER(5) DEFAULT 0 NOT NULL,
STEP NUMBER(3) DEFAULT 0 NOT NULL,
DEPTH NUMBER(3) DEFAULT 0 NOT NULL,
REGDATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
IP VARCHAR2(20) NOT NULL,
CONSTRAINT BOARD_PK PRIMARY KEY(NUM)
);

SELECT * FROM BOARD;
DESC BOARD;


CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE 
NOCACHE
NOCYCLE;

COMMIT;
