-- 회원 테이블 --

CREATE TABLE STUDENT(
ID          VARCHAR2(12)    NOT NULL,
PASS        VARCHAR2(12)    NOT NULL,
NAME        VARCHAR2(10)    NOT NULL,
PHONE1      VARCHAR2(3)     NOT NULL,
PHONE2      VARCHAR2(4)     NOT NULL,
PHONE3      VARCHAR2(4)     NOT NULL,
EMAIL       VARCHAR2(30)    NOT NULL,
ZIPCODE     VARCHAR2(7)     NOT NULL,
ADDRESS1    VARCHAR2(120)   NOT NULL,
ADDRESS2    VARCHAR2(50)    NOT NULL,
CONSTRAINT STUDENT_PK PRIMARY KEY(ID)
);

SELECT * FROM STUDENT;
DESC STUDENT;
COMMIT;


-- 우편번호 테이블-

CREATE TABLE ZIPCODE (
SEQ         NUMBER(5)       NOT NULL,
ZIPCODE     VARCHAR2(7)     NOT NULL,
SIDO        VARCHAR2(6)     NOT NULL,
GUGUN       VARCHAR2(30)    NOT NULL,
DONG        VARCHAR2(50)    NOT NULL,
RI          VARCHAR2(80),
BUNJI       VARCHAR2(20),
CONSTRAINT ZIPCODE_PK PRIMARY KEY(SEQ)
);

SELECT * FROM ZIPCODE;
DESC ZIPCODE;
COMMIT;

DROP TABLE ZIPCODE;