CREATE TABLE PROPRAC_NOTICE(
NO1         NUMBER(7)       NOT NULL,
TITLE1      VARCHAR2(200)   NOT NULL,
CONTENT1    VARCHAR2(2000)  NOT NULL,
READCOUNT1  NUMBER(5)       NOT NULL,
REGDATE     TIMESTAMP(6)    DEFAULT SYSDATE NOT NULL,
CONSTRAINT PROPRAC_NOTICE_PK PRIMARY KEY(NO1)
);

SELECT * FROM PROPRAC_NOTICE;

DROP TABLE PROPRAC_NOTICE;