CREATE TABLE STOCK (
NUM     NUMBER(5)   NOT NULL,
VALUE   NUMBER(5)   DEFAULT 0 NOT NULL,
CONSTRAINT STOCK_PK PRIMARY KEY(NUM)
);

COMMIT;

SELECT * FROM STOCK;

DESC STOCK;

INSERT INTO STOCK VALUES(1, 390);
INSERT INTO STOCK VALUES(2, 403);
INSERT INTO STOCK VALUES(3, 302);
INSERT INTO STOCK VALUES(4, 252);
INSERT INTO STOCK VALUES(5, 370);
INSERT INTO STOCK VALUES(6, 290);
INSERT INTO STOCK VALUES(7, 305);
INSERT INTO STOCK VALUES(8, 300);
INSERT INTO STOCK VALUES(9, 380);
INSERT INTO STOCK VALUES(10, 280);