CREATE TABLE VISIT (
NO          NUMBER(5) NOT NULL,
WRITER      VARCHAR2(20) NOT NULL,
MEMO        VARCHAR2(4000) NOT NULL,
REGDATE     DATE NOT NULL,
CONSTRAINT VISIT_PK PRIMARY KEY(NO)
);

DESC VISIT;
SELECT * FROM VISIT;

CREATE SEQUENCE VISIT_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCACHE
NOCYCLE;
COMMIT;


SELECT * FROM VISIT;
SHOW USER;