SELECT * FROM TAB;

CREATE TABLE DEPARTMENT_PRACTICE(
DEPTNO NUMBER(3) NOT NULL,
DNAME VARCHAR2(40) NOT NULL,
COLLEGE NUMBER(3) NOT NULL,
LOC VARCHAR2(20) NOT NULL
);
SELECT * FROM DEPARTMENT;

DESC DEPARTMENT_PRACTICE;
DROP TABLE DEPARTMENT_PRACTICE;
SELECT * FROM PROFESSOR;
DELETE FROM DEPARTMENT;


CREATE TABLE PROFESSOR_PRACTICE(
PROFNO NUMBER(4) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
ENAME VARCHAR2(20) NOT NULL,
POSITION VARCHAR2(40) NOT NULL,
SAL NUMBER(7,2) NOT NULL,
HIREDATE DATE,
AGE NUMBER(2) NOT NULL,
DEPTNO NUMBER(3) NOT NULL
);