-- 사원번호, 사원명, 직급, 부서번호로 구성하되, 사원번호와 사원명에 NOT NULL 조건을 지정
DROP TABLE EMP01;
PURGE RECYCLEBIN;

CREATE TABLE EMP01(
EMPNO NUMBER(4) NOT NULL,
ENAME VARCHAR2(100) NOT NULL,
JOB VARCHAR2(100), 
DEPTNO NUMBER(2)
);

SELECT * FROM EMP01;

INSERT INTO EMP01 VALUES(1111, 'tlarbgh', 't', 10);

-- EMP01의 DEPTNO를 기본키로 EMP02를 받아오시오.

CREATE TABLE EMP01(
DEPTNO NUMBER(2) REFERENCES EMP02(DEPTNO),
ENAME VARCHAR(10)
);

CREATE TABLE EMP02(
EMPNO NUMBER(4),
ENAME VARCHAR(10),
JOB VARCHAR(14),
HIREDATE DATE,
DEPTNO NUMBER(2) PRIMARY KEY
);

SELECT * FROM EMP02;
INSERT INTO EMP02 VALUES(1111, 'sim', 'CHAIRMAN', SYSDATE, 10);
SELECT * FROM EMP01;
INSERT INTO EMP01 VALUES(10, 'KYU');

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='EMP02';
SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME='EMP02';