CREATE TABLE PRAC (
ID          VARCHAR2(20) NOT NULL,
PASS        VARCHAR2(20) NOT NULL,
NAME        VARCHAR2(20) NOT NULL,
PHONE1      VARCHAR2(5)  NOT NULL,
PHONE2      VARCHAR2(5)  NOT NULL,
PHONE3      VARCHAR2(5)  NOT NULL,
EMAIL       VARCHAR2(50) NOT NULL,
ZIPCODE     VARCHAR2(10) NOT NULL,
ADDRESS1    VARCHAR2(50) NOT NULL,
ADDRESS2    VARCHAR2(50) NOT NULL,
CONSTRAINT PRAC_PK PRIMARY KEY(ID)
);

SELECT * FROM PRAC;