CREATE TABLE PROPRAC_FREE_REPLY(
CNO              NUMBER(5)       NOT NULL,
CID              VARCHAR2(30) ,
CCONTENT         VARCHAR2(4000)  NOT NULL,
CDATE            TIMESTAMP(6)    DEFAULT SYSDATE NOT NULL,
PARENTNO         NUMBER(5)       DEFAULT 0 NOT NULL,
CCOUNT           NUMBER(5)       DEFAULT 0 NOT NULL
);

SELECT * FROM PROPRAC_FREE_REPLY;

DROP TABLE PROPRAC_FREE_REPLY;

CREATE SEQUENCE PROPRAC_FREE_REPLY_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCACHE
NOCYCLE;

COMMIT;

DESC PROPRAC_FREE_REPLY;